### PR TITLE
Added Trigger for the workflow on pull request events

### PR DESCRIPTION
**Pull request by mtwn105**
Fixing Issue #14

### CODE REVIEW

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
LGTM but we need the same things also here https://github.com/clightning4j/lite-bitcoin-rpc/blob/main/.github/workflows/testing.yml

**Comment by mtwn105** [comment]
@vincenzopalazzo Done 🍡

**Review by vincenzopalazzo — APPROVED** [review]
LGTM, thanks for your amazing work

@vincenzopalazzo approve this PR.

**Comment by vincenzopalazzo** [comment]
Sorry but I revert your pr because it is not on the main branch but it is on dev. This doesn't make much sense to me.

https://github.com/clightning4j/lite-bitcoin-rpc/pull/16

**Pull request merged**
